'use client'

import { useEffect, useState } from 'react'
import { Bell, Check, Database, HardDrive, Link2, LoaderCircle, LockKeyhole, Unplug } from 'lucide-react'

export function SettingsPanel() {
  const [notifications,setNotifications] = useState(true); const [compact,setCompact] = useState(false); const [saved,setSaved] = useState(false)
  const [drive,setDrive] = useState<{loading:boolean;connected:boolean;email:string|null}>({loading:true,connected:false,email:null})
  useEffect(() => { const timer = window.setTimeout(() => { setNotifications(localStorage.getItem('apollo:notifications') !== 'off'); setCompact(localStorage.getItem('apollo:compact') === 'on') }, 0); fetch('/api/integrations/google-drive').then(r=>r.json()).then(v=>setDrive({loading:false,connected:Boolean(v.connected),email:v.email??null})).catch(()=>setDrive({loading:false,connected:false,email:null})); return () => window.clearTimeout(timer) },[])
  function persist(){localStorage.setItem('apollo:notifications',notifications?'on':'off');localStorage.setItem('apollo:compact',compact?'on':'off');document.documentElement.dataset.density=compact?'compact':'standard';setSaved(true);setTimeout(()=>setSaved(false),1800)}
  async function disconnectDrive(){setDrive(v=>({...v,loading:true}));await fetch('/api/integrations/google-drive',{method:'DELETE'});setDrive({loading:false,connected:false,email:null})}
  return <div className="settings-grid"><section className="ops-panel settings-panel"><header><span>WORKSPACE PREFERENCES</span><b>LOCAL DEVICE</b></header><label><div><Bell/><span><strong>Mission notifications</strong><small>Surface completed or blocked execution states.</small></span></div><input type="checkbox" checked={notifications} onChange={e=>setNotifications(e.target.checked)}/></label><label><div><Database/><span><strong>Compact mission density</strong><small>Reduce vertical spacing in operational lists.</small></span></div><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/></label><button onClick={persist}>{saved?<><Check/>Saved</>:<>Save preferences</>}</button></section><section className="ops-panel settings-panel"><header><span>DELIVERY INTEGRATIONS</span><b>{drive.connected?'CONNECTED':'ACTION REQUIRED'}</b></header><div className="boundary-row"><HardDrive/><div><strong>Google Drive custody</strong><small>{drive.loading?'Checking secure connection…':drive.connected?`Connected${drive.email?` as ${drive.email}`:''}. Drafts are delivered to the controlled APOLLO folder.`:'Reconnect Drive to restore controlled draft delivery.'}</small></div></div>{drive.loading?<button disabled><LoaderCircle/>Checking…</button>:drive.connected?<button onClick={disconnectDrive}><Unplug/>Disconnect Drive</button>:<button onClick={()=>{window.location.href='/api/integrations/google-drive?action=connect'}}><Link2/>Connect Google Drive</button>}</section><section className="ops-panel settings-panel"><header><span>RELEASE BOUNDARIES</span><b>INTERNAL</b></header><div className="boundary-row"><LockKeyhole/><div><strong>Billing isolated</strong><small>No payment processor connected; internal-mode boundary enforced.</small></div></div><div className="boundary-row"><HardDrive/><div><strong>Evidence custody</strong><small>Private object storage, hashes, expiring retrieval, and user ownership.</small></div></div><div className="boundary-row"><Database/><div><strong>Durable specifications</strong><small>Every accepted change creates an immutable numbered version.</small></div></div></section></div>
}
