import { mkdir, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import type { Template } from '../lib/apollo/templates'

type RuntimeModule = Record<string, unknown> & { default?:Record<string, unknown> }
function exportsOf(module:RuntimeModule):Record<string, unknown> { return module.default ?? module }
const pdfExports = exportsOf(await import('../lib/apollo/pdf') as RuntimeModule)
const brandExports = exportsOf(await import('../lib/apollo/brands') as RuntimeModule)
const packageExports = exportsOf(await import('../lib/apollo/packages-loader') as RuntimeModule)
const orchestrateExports = exportsOf(await import('../lib/apollo/orchestrate') as RuntimeModule)
const { buildPdf } = pdfExports as typeof import('../lib/apollo/pdf')
const { loadBrand, loadBrandPalette } = brandExports as typeof import('../lib/apollo/brands')
const { findDeliverable, getModule, getSchema, getStylesForIndustry } = packageExports as typeof import('../lib/apollo/packages-loader')
const { orchestrate, chooseLayoutForSlug, shouldRenderToc } = orchestrateExports as typeof import('../lib/apollo/orchestrate')

const FIXTURES: Record<string, Record<string, unknown>> = {
  'contract-intelligence-review': {
    review_perspective:'Customer purchasing a vehicle service contract', review_goal:'Understand current coverage, preserve every claim right, identify exclusions and deadlines, and obtain the full value of the purchased protection.', as_of_date:'2026-09-15', jurisdiction:'Massachusetts',
  },
  'contract-package': {
    contract_type:'Professional Services Agreement', party_a_name:'Northstar Fabrication LLC', party_a_role:'Client', party_b_name:'On Spot Solutions LLC', party_b_role:'Consultant',
    scope_of_agreement:'Field inspection, corrective-work documentation, and final quality-control reporting for the Northstar facility modernization program.', governing_law:'Commonwealth of Massachusetts', term_length:'September 14, 2026 through December 31, 2026',
  },
  proposal: {
    prospect_organization:'Northstar Fabrication LLC', proposal_date:'2026-09-14', problem_statement:'Northstar requires an evidence-grounded field assessment and documented remediation plan before capital approval.', our_understanding:'The client needs a decision-ready package linking observed conditions, corrective actions, ownership, schedule, and acceptance criteria.',
    win_themes:'Evidence before assertion\nField-to-desk speed\nAccountable closeout\nDecision-ready clarity', proposed_methodology:'1. Mobilize and validate evidence\n2. Assess conditions and document findings\n3. Engineer prioritized corrective actions\n4. Verify completion and deliver the controlled record', risks_and_mitigations:'Site access constraints | Confirm access window before mobilization\nIncomplete records | Flag unsupported claims and maintain an open-decision register\nSchedule compression | Sequence critical-path observations first', assumptions:'Client provides safe site access\nClient designates one decision authority\nExisting records are supplied before field mobilization', pricing_model:'fixed-fee', pricing_detail:'Fixed fee: $18,750\n25% at authorization\n50% after field assessment\n25% at accepted final delivery', validity_period_days:30, next_steps_call_to_action:'Approve the proposed scope and authorize preparation of the engagement letter by October 14, 2026.',
  },
  'federal-proposal': {
    solicitation_number:'FAKE-APOLLO-2026-001', solicitation_title:'Facilities Condition Intelligence Support', issuing_agency:'United States Department of Example — Pilot Evaluation Office', offeror_name:'On Spot Solutions LLC', naics_code:'541611', set_aside:'Small Business',
    technical_approach_summary:'Use controlled evidence intake, field verification, traceable findings, and acceptance-tested reporting. Every claim maps to a supplied source or is labeled as an assumption.', management_approach_summary:'A program manager owns delivery, a field lead controls collection, and an independent reviewer verifies compliance before release.', past_performance_summary:'Northstar pilot | Multi-site field assessment and closeout documentation | Delivered traceable reports and an executive action register on schedule.',
  },
  'cash-flow-budget-package': {
    entity_name:'Northstar Fabrication LLC', forecast_period:'October 2026 through March 2027',
    base_case_lines:'Oct 2026 | 250000 | 185000 | 172000 | 13000 | 263000\nNov 2026 | 263000 | 192000 | 181000 | 11000 | 274000\nDec 2026 | 274000 | 215000 | 207000 | 8000 | 282000\nJan 2027 | 282000 | 178000 | 196000 | -18000 | 264000\nFeb 2027 | 264000 | 204000 | 190000 | 14000 | 278000\nMar 2027 | 278000 | 221000 | 205000 | 16000 | 294000',
    scenario_summary:'Best | 338000 | 250000 | 1285000 | 1197000\nBase | 294000 | 250000 | 1195000 | 1151000\nWorst | 205000 | 198000 | 1080000 | 1125000', key_assumptions:'Opening cash is $250,000\nCustomer receipts follow the approved aging schedule\nPayroll occurs biweekly\nNo unapproved capital purchases are included\nScenario values are management-provided planning estimates',
  },
  invoice: {
    invoice_number:'ONS-2026-0914-01', statement_type:'invoice', invoice_date:'2026-09-14', due_date:'2026-10-14', payment_terms_label:'Net 30', currency:'USD', bill_to_name:'Northstar Fabrication LLC', bill_to_address:'100 Industrial Way\nWorcester, MA 01608', supplier_tax_id:'04-1234567',
    line_items:'Field condition assessment | 1 | 8500.00 | taxable\nControlled QC report package | 1 | 4250.00 | taxable\nExecutive decision briefing | 2 | 1250.00 | non-taxable', tax_rate_percent:6.25, late_payment_interest_percent_monthly:1.5, payment_methods:'ACH to account ending 4421\nCompany check payable to On Spot Solutions LLC', billing_contact_name:'Avery Morgan', billing_contact_email:'billing@on-spot.solutions', customer_po_number:'NSF-PO-1047', contract_reference:'Northstar Modernization Services Agreement dated 2026-08-01', remit_to_name:'On Spot Solutions LLC', remit_to_address:'Boston, Massachusetts', tax_jurisdiction:'Massachusetts',
  },
  'change-order': {
    change_order_number:'CO-003', original_contract_title:'Northstar Facility Modernization Agreement', original_contract_date:'2026-06-01', original_contract_sum_dollars:425000, prior_change_orders_total_dollars:18500, original_completion_date:'2026-11-30', prior_change_orders_days_total:5, client_name:'Northstar Fabrication LLC', change_date:'2026-09-14', cause_of_change:'unforeseen-condition',
    cause_description:'During controlled demolition, the field team documented concealed deteriorated feeder conduit not shown in the issued drawings. Replacement is required before the approved equipment can be energized safely.', scope_changes:'Additions | Remove and replace 180 linear feet of deteriorated feeder conduit; provide new supports and conductors; perform insulation-resistance testing\nRemovals | None\nModifications | Resequence the east electrical-room turnover after corrective work', cost_breakdown:'Electrical labor | 96 hours | 145.00 | 13920.00\nConduit and fittings | 1 lot | 7850.00 | 7850.00\nConductors | 1 lot | 6200.00 | 6200.00\nTesting subcontractor | 1 lot | 2400.00 | 2400.00\nEquipment | 1 lot | 1150.00 | 1150.00\nOverhead and profit | 1 lot | 4728.00 | 4728.00', cost_impact_dollars:36248, schedule_impact_days:7, effective_date:'2026-09-15',
  },
  quote: {
    customer_name:'Northstar Fabrication LLC', customer_address:'100 Industrial Way\nWorcester, MA 01608', quote_date:'2026-09-14', valid_until:'2026-10-14', scope_summary:'Provide a controlled electrical-room condition assessment, corrective-work verification, and executive closeout package for the Northstar East Plant.',
    line_items:'Field condition assessment | 1 | 8500.00\nCorrective-work verification | 2 | 3250.00\nExecutive closeout package | 1 | 4750.00', payment_terms:'50% deposit / 50% on completion',
  },
  fsr: {
    work_order_number:'WO-NSF-1047', site_name:'Northstar East Plant', site_address:'100 Industrial Way, Worcester, MA 01608', customer_contact_onsite:'Avery Morgan, Facilities Director', visit_date:'2026-09-14', arrival_time:'07:00', departure_time:'16:30', technician_name:'Morgan Reed', equipment_asset_id:'EER-FDR-A-001', equipment_make_model:'Square D Power-Zone 4 switchgear',
    issue_reported:'Intermittent insulation-resistance alarm after replacement of concealed feeder conduit.', work_performed:'07:00 | Verified work permit and lockout/tagout\n07:25 | Inspected replacement conduit and conductor terminations\n09:10 | Performed insulation-resistance testing phase-to-phase and phase-to-ground\n11:20 | Corrected loose control-terminal connection\n13:15 | Repeated functional and insulation-resistance tests\n15:45 | Reviewed results with customer contact and secured equipment', warranty_status:'not-applicable', time_on_site_hours:9.5, follow_up_required:'none',
  },
  'incident-report': {
    incident_date:'2026-09-14', incident_time:'10:42', location:'Northstar East Plant — east electrical corridor', severity:'near-miss', reporter_name:'Alex Morgan', reporter_role:'Quality Control Lead',
    incident_description:'At 10:42, a material cart entered the marked electrical work boundary while conduit installation was underway. The spotter stopped movement before the cart contacted personnel, equipment, or energized systems. No injury, damage, or release occurred.', immediate_actions_taken:'Stopped work and cart movement\nConfirmed all personnel were clear\nRe-established the barricade and controlled access point\nConducted a crew reset before resuming work', notifications_made:'10:45 | Site superintendent notified\n10:52 | Client facilities representative notified\n11:05 | Safety manager notified', contributing_factors:'Access control | Temporary barricade had been moved for material delivery\nCommunication | Delivery route change was not included in the morning coordination brief', corrective_actions_immediate:'Assigned a dedicated access attendant\nMoved material staging outside the electrical boundary\nAdded delivery-route verification to the daily pre-task plan', investigation_status:'final-report', preparer_name:'Alex Morgan',
  },
  nda: {
    agreement_direction:'mutual', disclosing_party_name:'Northstar Fabrication LLC', disclosing_party_entity_type:'llc', disclosing_party_state:'Massachusetts', disclosing_party_address:'100 Industrial Way, Worcester, MA 01608', receiving_party_name:'On Spot Solutions LLC', receiving_party_entity_type:'llc', receiving_party_state:'Massachusetts', receiving_party_address:'Boston, Massachusetts', effective_date:'2026-09-14',
    purpose:'Evaluate and execute a controlled field-intelligence and operational-reporting pilot.', subject_matter:'Facility conditions, operating procedures, technical records, pricing, personnel information, pilot results, and non-public business plans.', marking_requirement:'all-non-public', disclosure_period_years:2, confidentiality_period_years:5, governing_state:'Massachusetts', jurisdiction_county:'Worcester County, Massachusetts', include_non_solicitation:'no', include_non_circumvention:'no', attorneys_fees:'prevailing-party', jury_waiver:'yes', assignment_policy:'consent-required',
  },
  'compliance-report': {
    organization_name:'Northstar Fabrication LLC', regulatory_framework:'OSHA 29 CFR 1910 — electrical safety and control of hazardous energy', assessment_scope:'East Plant electrical-maintenance procedures, lockout/tagout records, qualified-person training, equipment labeling, and contractor coordination.', assessment_period:'September 1–14, 2026', current_compliance_status:'Core lockout/tagout controls are documented and used. Two procedural gaps remain: delivery-route coordination is not formally included in pre-task planning, and the annual qualified-person roster review lacks a documented approval record.', key_concerns:'Uncontrolled boundary access during material delivery\nIncomplete annual approval evidence for the qualified-person roster\nInconsistent retention location for contractor coordination records',
  },
  'board-report': {
    organization_name:'Northstar Fabrication LLC', reporting_period:'Third Quarter 2026', report_type:'Pilot authorization and operating review', financial_highlights:'Revenue: $18.4M, 4.2% above plan\nOperating margin: 12.8%, 0.6 points below plan\nAvailable cash: $2.94M\nPilot authorization requested: $97,750 including contingency', strategic_initiatives:'East Plant modernization | On schedule | Electrical corrective work in progress\nField-intelligence pilot | Decision required | 90-day controlled deployment ready\nSupplier resilience | At risk | Secondary-source qualification due October 31', key_risks:'Electrical turnover delay | Medium | Operations Director | Weekly critical-path review\nEvidence fragmentation | High | CIO | Approve controlled pilot\nSingle-source controls supplier | High | Procurement Director | Qualify alternate supplier',
  },
  'business-plan': {
    company_name:'Northstar Field Intelligence Inc.', industry_sector:'Enterprise field-operations software',
    business_description:'A controlled enterprise platform that converts mixed field evidence into approved, decision-ready operational publications with durable source, approval, delivery, and revision lineage.',
    target_market:'Industrial operators, infrastructure contractors, regulated field-service organizations, and government program teams with high-consequence reporting workflows.',
    revenue_model:'Usage-priced professional deliverables, enterprise control-plane subscriptions, implementation services, and optional private-cloud or dedicated-environment support.',
    competitive_advantage:'Deliverable-specific specialist orchestration; evidence-before-assertion controls; durable approved specifications; brand-locked publication; owner-scoped external custody; and auditable regeneration rather than disposable chat output.',
    funding_stage:'Pre-seed internal pilot; seeking $2.5 million to complete enterprise security, design-partner pilots, and specialist catalog validation over 18 months.',
    team_overview:'Jordan Lee | Chief Executive Officer | Industrial operations and commercial delivery\nMorgan Reed | Chief Product Officer | Enterprise workflow systems\nAvery Chen | Field Operations Lead | Quality, safety, and compliance',
    current_revenue:'Pre-revenue product; parent-company professional services revenue is not attributed to this venture.', current_customers:'One internal design partner and three planned external pilot organizations.',
    key_metrics:'37 controlled deliverable classes\n24 live golden archetypes validated before this batch\n100% version lineage across tested regeneration flights\n35% target reduction in administrative cycle time', geographic_focus:'United States industrial and infrastructure market, beginning in the Northeast.', projection_timeframe:'2027–2031',
  },
  'market-analysis': {
    target_market:'United States industrial field-operations and regulated infrastructure organizations with 250–10,000 employees.',
    analysis_purpose:'Determine whether Northstar should authorize a design-partner launch for a controlled field-intelligence publication platform and identify the most defensible initial buyer segment.',
    company_name:'Northstar Field Intelligence Inc.', product_or_service:'Enterprise mission workflow that ingests mixed field evidence and produces governed, branded, decision-ready reports with approval and revision lineage.', geographic_scope:'United States, with initial emphasis on Massachusetts, New England, and Mid-Atlantic industrial corridors.',
    key_questions:'Which buyer has the highest cost of delayed field reporting?\nWhich workflows require evidence provenance and accountable approval?\nWhich alternatives are already funded?\nWhat entry wedge supports a 90-day paid pilot?',
    known_competitors:'General-purpose AI assistants; field-management suites; document automation vendors; manual internal reporting teams.', current_market_position:'Internal-pilot product with validated publication mechanics but no external commercial deployment.', budget_for_entry:'$500,000 controlled launch budget.', timeline_for_decision:'Pilot authorization by October 31, 2026; first external design partner by January 2027.',
    data_sources:'Management-provided pilot observations and planning assumptions only. Market-size figures must be labeled as estimates pending third-party validation.',
  },
  'investor-memo': {
    target_company:'Northstar Field Intelligence Inc.', sector:'Enterprise AI workflow and field operations', deal_type:'Series Seed preferred equity',
    investment_thesis:'A governed mission system can occupy the gap between general-purpose AI and systems of record by turning high-consequence field evidence into approved deliverables with provenance, brand control, and immutable revision history.',
    financial_overview:'Pre-revenue. Proposed raise: $2.5M. Planned 18-month use: 45% engineering and security, 25% customer pilots and implementation, 15% specialist validation, 10% operations, 5% contingency. No valuation or return assumptions have been approved.',
    risk_factors:'Pre-revenue product and unproven willingness to pay\nDependency on external AI, storage, and hosting providers\nEnterprise security and procurement requirements are not yet complete\nDocument-quality expectations vary by profession\nPotential liability from unsupported or stale source material',
    fund_name:'Example Industrial Systems Fund I', deal_size:'Potential $750,000 participation in a $2.5 million round.', management_assessment:'Founder-market fit is strong in field delivery and high-quality client documentation; enterprise software scaling experience requires augmentation.', due_diligence_status:'Product architecture and internal-pilot artifacts reviewed; security audit, reference calls, cap table, and customer discovery remain open.', investment_committee_date:'2026-10-15',
  },
  'investor-update': {
    company_name:'Northstar Field Intelligence Inc.', reporting_period:'September 2026',
    key_metrics:'37 deliverable classes in active catalog\n30 live golden archetypes validated including this batch target\n26 browser journeys passing\n280 unit and contract tests passing\n$2.94M illustrative customer cash position is test data, not company cash',
    highlights:'Completed governed regeneration and telemetry lineage\nValidated Google Drive owner-scoped custody\nAdded secure ZIP field-evidence intake\nConverted field, financial, legal, commercial, and executive formats to specialist publication layouts',
    challenges:'External design-partner evidence is not yet available\nEnterprise security review remains ahead of public launch\nProvider dependency advisories require upstream Workflow remediation\nCommercial pricing requires measured production cost data',
    priorities_next_period:'Complete remaining golden deliverable classes\nRun two controlled external design-partner missions\nCommission security and privacy readiness review\nInstrument per-deployment cost and cycle time',
    ceo_name:'Jordan Lee', cash_position:'Runway and company cash are not yet reported; pre-seed planning only.', product_updates:'Mission Control, evidence custody, approval, durable execution, telemetry, revision, and notification recovery are operating in the internal pilot.', team_updates:'Enterprise security and implementation leadership searches are planned after financing.', fundraising_status:'Preparing a $2.5 million seed process after completion of the internal pilot gate.', asks_of_investors:'Introduce two industrial design partners with regulated field-reporting workflows\nRecommend an enterprise security advisor experienced in AI systems',
  },
  'audit-readiness': {
    organization_name:'Northstar Fabrication LLC', audit_type:'SOC 2 Type I readiness assessment', audit_framework:'AICPA Trust Services Criteria — Security, Availability, and Confidentiality', target_audit_date:'2027-03-31',
    scope_description:'APOLLO mission intake, evidence custody, approved specification, document generation, review, notification, telemetry, administrative access, and supporting cloud services.',
    current_readiness:'Core owner-scoped access, durable approval state, artifact lineage, secret separation, and failure recovery are implemented. Formal control ownership, periodic access review evidence, vendor-risk files, incident exercises, and policy approval records remain incomplete.',
    prior_audit_results:'No prior SOC examination. Internal technical controls were reviewed during the September 2026 pilot.', auditor_firm:'To be selected through a controlled request for proposal.',
    key_controls:'Logical access | Owner-scoped authorization and row-level security | Operating\nChange management | Git-reviewed deployment lineage | Operating\nEvidence custody | Immutable source metadata and checksums | Operating\nIncident response | Failure notification and recovery workflow | Partially operating\nVendor management | Provider inventory and review | Design required',
    known_gaps:'No approved control matrix owner roster\nAccess-review cadence not evidenced\nVendor risk assessments incomplete\nIncident tabletop not yet performed\nPolicy approval and annual review workflow not established',
    system_landscape:'Vercel application and workflows\nSupabase database, authentication, and storage\nAnthropic model API\nGoogle Drive owner-scoped artifact custody\nGitHub source and deployment integration', classification:'Confidential — internal readiness planning',
  },
  'legal-memo': {
    client_name:'On Spot Solutions LLC', opposing_party:'Northstar Fabrication LLC — hypothetical counterparty', jurisdiction:'Commonwealth of Massachusetts',
    legal_issue:'For internal issue spotting only: whether a hypothetical services agreement permits suspension of disputed work and recovery of undisputed invoices after a client withholds all payment based on a documented but limited deliverable objection.',
    relevant_statutes:'Massachusetts General Laws chapter 30, section 39G may inform prompt-payment concepts for certain public works but applicability to this hypothetical private services agreement is unverified. Contract text, common-law breach principles, waiver, notice, cure, and any applicable consumer or licensing rules require licensed Massachusetts counsel review.',
    desired_outcome:'Identify the contract facts, legal questions, risk-preserving immediate actions, and records counsel needs before advising whether to continue, suspend, negotiate, or pursue collection. Do not provide a definitive legal conclusion.',
    deadline:'2026-09-18', audience:'Internal executive team and retained Massachusetts counsel.', confidentiality_level:'Attorney review draft — privileged status not established merely by this label.',
    prior_proceedings:'No complaint, demand, lien, arbitration, or court filing. One written objection was received; the company has not yet issued a reservation-of-rights notice.',
  },
  'financial-statements-package': {
    entity_name:'Northstar Fabrication LLC', fiscal_year_end:'December 31, 2026', basis_of_accounting:'us-gaap', opinion_type:'compilation',
    opinion_letter_body:"Management is responsible for the accompanying financial statements of Northstar Fabrication LLC, which comprise the balance sheets as of December 31, 2026 and 2025, and the related statements of operations and cash flows for the years then ended. We performed this compilation engagement in accordance with Statements on Standards for Accounting and Review Services promulgated by the Accounting and Review Services Committee of the AICPA. We did not audit or review the financial statements nor were we required to perform any procedures to verify the accuracy or completeness of the information provided by management. Accordingly, we do not express an opinion, a conclusion, nor provide any assurance on these financial statements.\n\nExample Accounting Partners LLP\nWorcester, Massachusetts\nFebruary 15, 2027",
    balance_sheet_lines:'Cash and cash equivalents | 2,940,000 | 2,310,000\nAccounts receivable, net | 3,180,000 | 2,860,000\nInventory | 1,420,000 | 1,270,000\nTotal current assets | 7,540,000 | 6,440,000\nProperty and equipment, net | 5,260,000 | 5,010,000\nTotal assets | 12,800,000 | 11,450,000\nAccounts payable | 1,760,000 | 1,590,000\nAccrued expenses | 820,000 | 770,000\nTotal current liabilities | 2,580,000 | 2,360,000\nLong-term debt | 3,100,000 | 3,450,000\nTotal liabilities | 5,680,000 | 5,810,000\nMembers equity | 7,120,000 | 5,640,000\nTotal liabilities and equity | 12,800,000 | 11,450,000',
    income_statement_lines:'Revenue | 18,400,000 | 16,950,000\nCost of revenue | (12,240,000) | (11,410,000)\nGross profit | 6,160,000 | 5,540,000\nOperating expenses | (3,805,000) | (3,690,000)\nOperating income | 2,355,000 | 1,850,000\nInterest and other expense | (210,000) | (235,000)\nIncome before taxes | 2,145,000 | 1,615,000\nIncome tax expense | (429,000) | (323,000)\nNet income | 1,716,000 | 1,292,000',
    cash_flow_lines:'Net income | 1,716,000 | 1,292,000\nDepreciation and amortization | 610,000 | 570,000\nChanges in working capital | (246,000) | (188,000)\nNet cash provided by operating activities | 2,080,000 | 1,674,000\nCapital expenditures | (860,000) | (790,000)\nNet cash used in investing activities | (860,000) | (790,000)\nDebt repayments | (350,000) | (300,000)\nMember distributions | (240,000) | (210,000)\nNet cash used in financing activities | (590,000) | (510,000)\nNet change in cash | 630,000 | 374,000',
  },
  'expense-report': {
    submitter_name:'Morgan Reed', period_start:'2026-09-01', period_end:'2026-09-14', business_purpose:'Northstar East Plant field assessment, corrective-work verification, and executive closeout.', manager_approver_name:'Avery Morgan',
    expense_lines:'2026-09-10 | Delta Air Lines | BOS to PIT field mobilization | Travel | 428.16 | Corporate card\n2026-09-10 | Enterprise | Site rental vehicle | Ground transportation | 286.40 | Corporate card\n2026-09-11 | Harbor Hotel | Two project nights | Lodging | 438.00 | Corporate card\n2026-09-11 | Field crew meal | Working dinner for four | Meals | 126.75 | Personal card\n2026-09-12 | FedEx Office | Controlled drawing set | Project supplies | 64.22 | Corporate card',
  },
  'personal-monthly': {
    person_name:'Jordan Lee — planning scenario', month_label:'September 2026', prepared_date:'2026-09-14',
    income_sources:'Salary, net | 9,850.00\nConsulting income, net | 2,400.00\nInterest income | 85.00',
    fixed_expenses:'Mortgage | 2,850.00\nUtilities | 410.00\nInsurance | 620.00\nVehicle payment | 585.00\nStudent loan | 475.00\nSavings transfer | 1,500.00',
    variable_expenses:'Groceries | 825.00\nFuel and transportation | 340.00\nDining | 425.00\nHousehold | 280.00\nHealth and wellness | 190.00\nDiscretionary | 375.00',
  },
  'one-pager': {
    company_name:'On Spot Solutions LLC', tagline:'Field intelligence at decision speed', target_audience:'Industrial operations leaders responsible for field execution, quality, and capital decisions.',
    value_proposition:'Convert field evidence into controlled, executive-ready reports while the work is still happening—without losing source provenance, approvals, or revision history.',
    key_features:'Multi-file and ZIP evidence intake\nSpecialist-guided mission calibration\nBrand-locked professional publication\nImmutable deployment and regeneration lineage\nGoogle Drive custody with owner-scoped access',
    problem_statement:'Critical observations reach decision-makers through scattered photos, emails, spreadsheets, and manually assembled reports. By the time leadership sees a complete record, the field condition may already have changed.', outcome_metrics:'35% target reduction in administrative cycle time during the Northstar pilot\n37 professional deliverable classes available through one controlled workflow\n100% of pilot regenerations retain version lineage', key_differentiators:'Evidence before assertion\nOne approved specification controls every deployment\nDeliverable-specific quality gates, not generic chat output\nPer-deliverable commercial model without seat-license friction', cta_primary:'Authorize a controlled 90-day pilot', contact_web:'https://on-spot.solutions', contact_email:'support@apollomc.ai',
  },
  'project-completion-notice': {
    issued_to:'Northstar Fabrication LLC — Facilities Department', project_name:'Northstar East Plant Electrical Upgrade', job_number:'NSF-ELEC-2026-014', issued_by:'Alex Morgan, Quality Control Lead, On Spot Solutions LLC', completion_date:'September 14, 2026 at 4:30 PM',
    completion_statement:'The replacement feeder conduit, conductors, supports, labeling, and required acceptance testing were completed within the authorized work area. Final verification found the installed scope acceptable subject to the continuing facility energization procedure.',
    scope_completed:'East electrical room feeder A | 180 LF | Installed, labeled, and tested PASS\nEast corridor supports | 24 EA | Installed at approved spacing; PASS\nFeeder conductors | 720 LF | Installed; insulation resistance PASS\nWork-area restoration | 1 LS | Complete and broom-clean',
    scope_boundary:'This notice covers the authorized conduit and conductor replacement through the east electrical-room termination points. Facility energization, operating release, and downstream equipment commissioning remain the responsibility of Northstar and its electrical authority.',
    site_conditions:'All installed conductors passed insulation-resistance testing\nAll labels match the approved panel schedule\nWork area restored and accepted\nNo recordable incidents', signatories:'Issued By | Alex Morgan | Quality Control Lead | On Spot Solutions LLC\nAcknowledged | Avery Morgan | Facilities Director | Northstar Fabrication LLC',
  },
  'tool-box-talk': {
    project_name:'Northstar East Plant Electrical Upgrade', job_number:'NSF-ELEC-2026-014', briefing_location:'East Plant laydown area', briefing_time:'2026-09-14 06:45', conducted_by:'Jordan Lee, Electrical Foreperson',
    attendees:'Jordan Lee | Foreperson\nMorgan Reed | Electrician\nAvery Chen | Electrician\nSam Ortiz | Apprentice',
    work_scope:'Remove concealed deteriorated feeder conduit, install replacement rigid metal conduit and conductors, perform continuity and insulation-resistance testing, and secure the de-energized work area.',
    hazards_controls:'Electrical energy | Verify lockout/tagout and absence of voltage before contact | Foreperson\nMaterial handling | Use rated lift and team lift for long conduit | Crew lead\nCutting and threading | Guards installed; eye and hand protection required | Operator\nBoundary intrusion | Maintain barricade and dedicated access attendant | Spotter\nHousekeeping | Remove cutoffs and trip hazards throughout shift | All personnel',
    emergency_procedures:'Stop work, maintain the safe boundary, call site emergency number 555-0100, and notify the superintendent. Assembly point is the north employee lot.',
  },
  sow: {
    project_name:'Northstar Facility Intelligence Pilot', client_name:'Northstar Fabrication LLC', provider_name:'On Spot Solutions LLC', project_description:'A controlled 90-day pilot that captures field evidence, engineers decision-ready deliverables, and preserves approval and revision lineage.', scope_of_work:'Configure controlled mission intake\nEstablish evidence and brand custody\nExecute six representative field and executive missions\nMeasure administrative cycle time\nDeliver pilot closeout and scale recommendation', project_timeline:'September 21 through December 20, 2026', total_budget:'Fixed fee of $97,750',
    key_milestones:'Kickoff | September 21, 2026\nControlled intake operational | October 5, 2026\nMidpoint review | November 5, 2026\nFinal readout | December 20, 2026', acceptance_criteria:'Mission intake | Required evidence and approval state retained | Demonstrated in live test\nControlled delivery | PDF stored in designated Drive folder | Artifact manifest verified\nRevision lineage | Prior version remains immutable | Reflight record verified', team_structure:'Jordan Lee | Executive sponsor\nAvery Morgan | Client program manager\nMorgan Reed | Provider program manager', out_of_scope:'Production payment activation\nEnterprise-wide rollout\nMigration of unrelated products or data', assumptions:'Client supplies authorized users and source records\nDrive access remains active\nPilot metrics are targets until measured', payment_schedule:'25% at kickoff\n50% at midpoint acceptance\n25% at final readout', client_pm_name:'Avery Morgan', provider_pm_name:'Morgan Reed', governing_state:'Massachusetts',
  },
  'daily-construction-report': {
    project_name:'Northstar East Plant Electrical Upgrade', job_number:'NSF-ELEC-2026-014', site_location:'100 Industrial Way, Worcester, MA', report_date:'2026-09-14', prepared_by:'Alex Morgan, Quality Control Lead', day_summary:'Feeder conduit replacement advanced on plan; east electrical room remained de-energized under approved lockout.',
    weather_conditions:'Clear | 68–77 F | No precipitation | Wind 6–10 mph | No impact to interior work', crew_roster:'Jordan Lee | Foreperson | 10 | OSHA 30\nMorgan Reed | Electrician | 10 | MA Journeyman 55231\nAvery Chen | Electrician | 9.5 | MA Journeyman 55902\nSam Ortiz | Apprentice | 9.5 | OSHA 10', work_performed:'07:00 | Pre-task plan and lockout verification completed\n07:25 | Removed 60 linear feet of deteriorated feeder conduit\n09:10 | Installed new supports at maximum 8-foot spacing\n11:15 | Installed 60 linear feet of new 2-inch rigid metal conduit\n14:20 | Pulled conductors and labeled both ends\n15:40 | Performed continuity test; all conductors passed\n16:15 | Area cleaned and secured; lockout retained', work_status:'East electrical room feeder A | 60 LF | Complete | Continuity test passed\nEast corridor feeder B | 0 LF | Not started | Scheduled 2026-09-15\nEquipment energization | 0% | On hold | Awaiting insulation-resistance test', equipment_on_site:'Conduit threader | Greenlee 535 | Operational\nMaterial lift | JLG 1930ES | Operational\nDigital multimeter | Fluke 87V | Calibration current', materials_consumed:'2-inch rigid metal conduit | 60 LF\n2-inch couplings | 12 EA\nConduit supports | 9 EA\nCopper conductors | 240 LF', issues_delays:'No schedule delay. Concealed wall access required one additional support location; resolved within planned work window.', safety_observations:'Lockout/tagout verified at start and close\nNo recordable incidents or near misses\nHousekeeping accepted at final walk', follow_up:'Perform insulation-resistance test before energization\nBegin east corridor feeder B replacement on 2026-09-15',
  },
  'meeting-minutes': {
    meeting_type:'project', meeting_title:'Northstar Pilot Authorization Meeting', meeting_date:'2026-09-14', meeting_time_start:'14:00', meeting_time_end:'15:10', meeting_location:'Northstar Executive Conference Room and Microsoft Teams', quorum_present:'yes', agenda_items:'Pilot objective and decision criteria\nScope and 90-day implementation plan\nBudget authorization\nGovernance and next actions',
    discussion_summary:'Pilot objective and decision criteria | Committee confirmed evidence provenance, cycle-time reduction, and accountable review as decision criteria.\nScope and 90-day implementation plan | Three-phase plan accepted subject to sponsor designation.\nBudget authorization | Committee reviewed $97,750 total authorization including $12,750 contingency.\nGovernance and next actions | Weekly program review and final capital-committee readout required.', action_items:'ACT-01 | Jordan Lee | Name executive sponsor | 2026-09-18 | Open\nACT-02 | Avery Morgan | Confirm pilot user roster | 2026-09-18 | Open\nACT-03 | Morgan Reed | Issue kickoff package | 2026-09-21 | Open', meeting_adjourned_at:'15:10', secretary_name:'Taylor Brooks', attendees_in_person:'Jordan Lee — Committee Chair\nAvery Morgan — Operations Director\nTaylor Brooks — Corporate Secretary', attendees_remote:'Morgan Reed — Program Director', motions_and_votes:'M-01 | Authorize the 90-day pilot and $97,750 expenditure | Moved by Avery Morgan | Seconded by Jordan Lee | 3 in favor, 0 opposed, 0 abstained | Adopted', next_meeting_date:'2026-10-05',
  },
  'tax-estimate': {
    taxpayer_name:'Jordan Lee — planning scenario', tax_year:2026, filing_status:'single', state_residence:'Massachusetts', deduction_method:'standard', prepared_by:'On Spot Solutions LLC — internal planning', prepared_date:'2026-09-14', gross_income_w2:185000, gross_income_1099_self_employment:42000, gross_income_investment:8500, gross_income_other:0, withholdings_ytd:39200, estimated_payments_ytd:12500, prior_year_tax_liability:47250, tax_credits:'Energy efficiency planning credit | 2500 | Eligibility not verified; exclude from payable estimate until confirmed',
  },
  'pitch-deck': {
    company_name:'Northstar Fabrication LLC', tagline:'Verified operations intelligence at decision speed', problem:'Industrial operators lose time and margin when field evidence arrives fragmented, late, and without accountable ownership.', solution:'A controlled mission workflow converts source evidence into reviewable operational decisions while preserving provenance and approval state.', business_model:'Enterprise platform license plus usage-priced controlled deliverables and implementation support.', traction:'3 internal pilot missions completed\n11 controlled draft deliveries\n5 verified regeneration flights\n37 supported professional deliverable types', team:'Jordan Lee | Chief Executive Officer | Industrial operations\nMorgan Reed | Chief Product Officer | Enterprise workflow systems\nAvery Chen | Field Operations Lead | Quality and compliance', fundraising_ask:'Seeking $2.5 million to complete enterprise security, pilot deployment, and specialist expansion over 18 months.',
  },
  'exec-presentation': {
    organization_name:'Northstar Fabrication LLC', presentation_topic:'Pilot operating review and authorization decision', audience:'Executive leadership and capital committee', key_message:'Authorize the controlled field-intelligence pilot because it shortens decision latency while preserving evidence provenance and accountable review.',
    context_and_background:'Field observations currently reach leadership through fragmented email, spreadsheets, and manually assembled reports. The proposed pilot introduces one controlled intake, review, and delivery chain.', desired_action:'Approve a 90-day internal pilot, designate an executive sponsor, and authorize the listed implementation workstreams.', presenter_name:'Jordan Lee, Program Director', presentation_date:'2026-09-14', time_limit:'20 minutes plus 10 minutes for questions',
    financial_data:'Pilot implementation: $85,000\nContingency: $12,750\nTotal authorization requested: $97,750\nTarget administrative time reduction: 35%', competitive_context:'The current alternative is a mix of general-purpose AI tools and manual document production without durable specification, evidence, approval, or regeneration state.', sensitive_topics:'All performance figures are pilot targets, not guaranteed outcomes. No unsupported savings claim may be presented as verified.',
  },
  'final-qc-report': {
    project_name:'Northstar Facility Modernization', job_number:'NSF-2026-014', project_period:'September 10–14, 2026', report_date:'2026-09-14', inspector:'Alex Morgan, Quality Control Lead', reference_documents:'Approved drawing A-101 Rev 3\nManufacturer installation instruction MI-44\nProject specification section 26 05 00', completion_statement:'The inspected installation is complete with the exceptions recorded in this report.', acceptance_criteria:'Circuit identification | Labels match approved panel schedule | Pass\nFastener torque | Manufacturer value of 35 in-lb | Pass\nConduit support spacing | Maximum 10 ft interval | Pass', test_results:'QC-01 | Main electrical room | Label schedule match | Pass\nQC-02 | Main electrical room | 35 in-lb measured torque | Pass\nQC-03 | East corridor | 8 ft maximum support interval | Pass',
  },
  'capability-statement': {
    company_name:'On Spot Solutions LLC', core_competencies:'Field condition assessments\nEvidence-controlled operational reporting\nQuality-control and closeout documentation\nProgram implementation support', naics_codes:'541611 — Administrative Management and General Management Consulting Services\n541330 — Engineering Services', differentiators:'Field-to-desk controlled reporting\nSource-level provenance\nImmutable review and revision lineage\nDecision-ready executive communication', past_performance_highlights:'Northstar Fabrication | Facility modernization QC | Controlled final report and corrective-action register\nRiverfront Center | Site assessment | Evidence-grounded proposal and implementation roadmap',
  },
}

const UPLOAD_FIXTURES:Record<string, Array<{ id:string; upload_kind:string; original_filename:string; content_type:string; size_bytes:number; caption:string|null; extracted_text:string; bytes:null }>> = {
  'contract-intelligence-review': [{
    id:'northstar-warranty-contract', upload_kind:'reference_doc', original_filename:'Northstar_Vehicle_Service_Contract.pdf', content_type:'text/plain', size_bytes:6400, caption:'Synthetic pilot contract — not a real customer agreement', bytes:null,
    extracted_text:`NORTHSTAR VEHICLE SERVICE CONTRACT — SAMPLE PILOT EVIDENCE
Contract No. NS-VSC-2026-0915. Customer: Jordan Example. Administrator: Northstar Protection LLC. Selling Dealer: Example Motors LLC. Covered Vehicle: 2024 Example Utility, VIN TEST000000000001. Purchase Date and Effective Date: September 15, 2026. Contract Price: $2,495. This synthetic agreement is for APOLLO testing only.

SECTION 1 — TERM AND MILEAGE. Coverage begins September 15, 2026 and expires at the earlier of September 15, 2031 or 75,000 vehicle miles. Odometer at purchase: 12,500 miles. Benefits apply only while the contract is active and all eligibility requirements are satisfied.

SECTION 2 — COVERED COMPONENTS. The Administrator will pay reasonable parts and labor for a covered mechanical breakdown of the engine, transmission, transfer case, drive axle, steering, suspension, electrical, air conditioning, fuel system, cooling system, and factory-installed navigation display, subject to exclusions and limits. The per-visit deductible is $100. If repairs are performed by the Selling Dealer, the deductible is reduced to $0. Aggregate benefits shall not exceed the vehicle's actual cash value immediately before the covered breakdown.

SECTION 3 — ADDITIONAL BENEFITS. Towing reimbursement is limited to $150 per covered breakdown. Rental vehicle reimbursement is limited to $50 per day for up to five days when approved covered labor exceeds eight hours. Trip interruption is limited to $100 per day for up to three days when a covered breakdown occurs more than 100 miles from the Customer's residence. Receipts are required and reimbursement requests must be submitted within 30 days after completion of the covered repair.

SECTION 4 — CUSTOMER DUTIES AND CLAIM PROCEDURE. The Customer must maintain the vehicle according to the manufacturer's schedule and retain itemized maintenance records and receipts. Before teardown or repair, the Customer or repair facility must call 800-555-0147 and obtain an authorization number. Emergency repairs when the office is closed may proceed only to prevent further damage and are limited to $500 without prior authorization; notice and receipts must be submitted within five business days. The Administrator may inspect the vehicle and request maintenance records. Failure to obtain authorization or provide requested records may result in denial.

SECTION 5 — EXCLUSIONS. This contract does not cover routine maintenance; pre-existing conditions; collision, theft, vandalism, fire, flood, or environmental damage; misuse, racing, commercial delivery use, or modifications not approved by the manufacturer; diagnostic charges when no covered breakdown is found; shop supplies; consequential damage; or repairs covered by a manufacturer's warranty, recall, insurance policy, or other service contract. Seals and gaskets are covered only when required in connection with a covered component repair.

SECTION 6 — CANCELLATION. The Customer may cancel at any time by written request delivered to the Selling Dealer. Cancellation within 30 days of purchase, if no claim has been paid, receives a full refund. Later cancellation receives a pro-rata refund based on elapsed time or mileage, whichever produces the lesser refund, less paid claims and a $50 administrative fee. If a financed contract is cancelled, the refund may be paid to the lienholder. The Administrator may cancel only for nonpayment, material misrepresentation, or substantial breach of duties and must provide at least 15 days' written notice stating the reason and effective date.

SECTION 7 — TRANSFER. The contract may be transferred once to a private purchaser of the covered vehicle. A transfer form, proof of sale, maintenance records, and a $75 fee must be received by the Administrator within 30 days after the vehicle sale. The contract may not be transferred to a dealer or in connection with a commercial resale.

SECTION 8 — DISPUTES AND GOVERNING LAW. Massachusetts law governs. The parties will first attempt informal resolution by written notice describing the dispute and requested remedy. If unresolved after 30 days, either party may pursue available remedies. Nothing in this section waives rights that cannot lawfully be waived. Notices to the Administrator must be sent by certified mail to 100 Sample Plaza, Boston, MA 02110, with a copy by email to claims@example.invalid.

SECTION 9 — ENTIRE AGREEMENT AND AMENDMENTS. This contract, the declarations page, and listed endorsements form the entire agreement. Changes are effective only in a written endorsement issued by the Administrator. Endorsement A, if attached, controls over conflicting terms. No Endorsement A was included in the supplied pilot evidence.

SECTION 10 — PRIVACY AND RECORDS. Claim and maintenance records may be retained for seven years after contract expiration. The Customer should retain the contract, declarations, authorization numbers, estimates, invoices, receipts, maintenance records, and all notices for the same period.`,
  }],
}

const requested = process.argv.slice(2)
const slugs = requested.length ? requested : Object.keys(FIXTURES)
const unknown = slugs.filter(slug => !FIXTURES[slug])
if (unknown.length) throw new Error(`Unknown pilot fixtures: ${unknown.join(', ')}`)
if (!process.env.ANTHROPIC_API_KEY) throw new Error('ANTHROPIC_API_KEY is required')

const brand = await loadBrand('on-spot-solutions')
const palette = await loadBrandPalette('on-spot-solutions')
if (!brand) throw new Error('On Spot Solutions pilot brand is unavailable')
const outputDir = path.join(tmpdir(), 'apollo-pilot-golden')
await mkdir(outputDir, { recursive:true })

const report: Array<Record<string, unknown>> = []
for (const slug of slugs) {
  const summary = findDeliverable(slug)
  const module = getModule(slug)
  const schema = getSchema(slug) as Record<string, unknown> | null
  if (!summary || !module || !schema) throw new Error(`Catalog resources unavailable for ${slug}`)
  const style = getStylesForIndustry(summary.industry_slug)[0]
  if (!style) throw new Error(`No style available for ${slug}`)
  const started = Date.now()
  const generated = await orchestrate({ slug, deliverableLabel:summary.label, industryLabel:summary.industry_label, module, schema, style, brand, fields:FIXTURES[slug], uploads:UPLOAD_FIXTURES[slug] ?? [] })
  const template: Template = { slug, label:summary.label, description:summary.description, category:summary.industry_slug, supports_images:true, has_signature_block:['sow','proposal','contract-package','engagement-letter','nda','change-order'].includes(slug), has_toc:shouldRenderToc(slug), layout:chooseLayoutForSlug(slug), fields:[], sections:module.sections.map(section => ({ id:section.key, title:section.label })), generation_notes:'' }
  const pdf = await buildPdf({ template, brand, inputs:FIXTURES[slug], contentHtml:generated.contentHtml, documentId:`PILOT-${slug.toUpperCase()}-20260914`, preparedDate:'September 14, 2026', palette })
  await writeFile(path.join(outputDir, `${slug}.pdf`), pdf)
  await writeFile(path.join(outputDir, `${slug}.html`), generated.contentHtml)
  report.push({ slug, model:process.env.APOLLO_MODEL_STRUCTURED_FILL || 'claude-sonnet-5', elapsed_ms:Date.now()-started, pdf_bytes:pdf.length, quality:generated.quality, warnings:generated.warnings })
  console.log(`${slug}: PASS (${pdf.length} bytes, score ${generated.quality.score})`)
}
await writeFile(path.join(outputDir, 'report.json'), JSON.stringify({ generated_at:new Date().toISOString(), output_dir:outputDir, results:report }, null, 2))
console.log(`Pilot golden matrix complete: ${outputDir}`)
