import { describe, expect, it } from 'vitest'
import { buildFullHtml } from '@/lib/apollo/pdf'
import type { LoadedBrand } from '@/lib/apollo/brands'
import type { Template } from '@/lib/apollo/templates'

const brand: LoadedBrand = {
  slug: 'on-spot-solutions',
  label: 'On Spot Solutions',
  logo_file: null,
  logo_path: null,
  logo_bytes: null,
  logo_mime: null,
  brand_md: '',
}

function template(slug: string, label: string, layout: Template['layout'] = 'contract'): Template {
  return {
    slug,
    label,
    layout,
    description: '',
    category: 'Test',
    supports_images: false,
    fields: [],
    sections: [],
    generation_notes: '',
  }
}

function render(selected: Template): string {
  return buildFullHtml({
    template: selected,
    brand,
    inputs: { entity_name: 'Northstar Fabrication', forecast_period: 'October–December 2026' },
    contentHtml: '<h1>Duplicate title</h1><h2>Forecast Details</h2><p>Verified content.</p>',
    documentId: 'DOC-1007',
    preparedDate: 'September 12, 2026',
  })
}

describe('packet cover invariant', () => {
  it('adds one branded cover to specialized financial packages', () => {
    const html = render(template('cash-flow-budget-package', 'Cash Flow Budget Package'))

    expect(html.match(/class="packet-cover"/g)).toHaveLength(1)
    expect(html).toContain('ON SPOT SOLUTIONS')
    expect(html).toContain('Northstar Fabrication &middot; October–December 2026')
    expect(html.indexOf('class="packet-cover"')).toBeLessThan(html.indexOf('class="ld-masthead"'))
    expect(html).not.toContain('Generated by APOLLO')
  })

  it('never leaks On Spot or APOLLO identity into a client-branded ledger packet', () => {
    const clientBrand: LoadedBrand = { ...brand, slug:'kit:northstar', label:'Northstar Fabrication' }
    const html = buildFullHtml({ template:template('cash-flow-budget-package', 'Cash Flow Budget Package'), brand:clientBrand, inputs:{ entity_name:'Northstar Fabrication', forecast_period:'FY 2027' }, contentHtml:'<h2>Forecast Details</h2><p>Verified content.</p>', documentId:'NOR-CASHFL-1007', preparedDate:'September 14, 2026' })
    expect(html).toContain('Northstar Fabrication')
    expect(html).not.toContain('On Spot Solutions')
    expect(html).not.toContain('Generated by APOLLO')
  })

  it('renders approved cash-flow schedules and assumptions without model rewriting', () => {
    const html = buildFullHtml({
      template:template('cash-flow-budget-package', 'Cash Flow Budget Package'),
      brand,
      inputs:{
        entity_name:'Northstar Fabrication',
        forecast_period:'October through December 2026',
        base_case_lines:'Oct 2026 | 250000 | 185000 | 172000 | 13000 | 263000\nNov 2026 | 263000 | 192000 | 181000 | 11000 | 274000',
        scenario_summary:'Base | 274000 | 250000 | 377000 | 353000',
        key_assumptions:'Opening cash is $250,000\nReceipts follow the approved aging schedule',
      },
      contentHtml:'<h2>Forecast Details</h2><p>Model narrative.</p>',
      documentId:'NOR-CASHFL-1007',
      preparedDate:'September 14, 2026',
    })
    expect(html).toContain('Approved forecast controls')
    expect(html).toContain('Oct 2026</td><td>250000</td><td>185000</td><td>172000</td><td>13000</td><td>263000')
    expect(html).toContain('Base</td><td>274000</td><td>250000</td><td>377000</td><td>353000')
    expect(html).toContain('Receipts follow the approved aging schedule')
  })

  it('renders approved contract facts and controlled source custody deterministically', () => {
    const html=buildFullHtml({
      template:template('contract-intelligence-review','Contract Intelligence Review'),brand,
      inputs:{contract_title:'Northstar Vehicle Service Contract',contracting_parties:'Northstar | Customer\nSecure Warranty | Administrator',effective_date:'2026-09-17',expiration_date:'2031-09-17',current_status:'Active',review_perspective:'Customer',review_goal:'Preserve every claim right',as_of_date:'2026-09-17',material_obligations:'Prior authorization | Section 4',commercial_rights_and_limits:'Towing | $150 | Section 8'},
      sourceNames:['Northstar_Vehicle_Service_Contract.pdf'],contentHtml:'<h2>Review</h2><p>Model narrative.</p>',documentId:'CIR-1007',preparedDate:'September 17, 2026',
    })
    expect(html).toContain('Approved contract controls')
    expect(html).toContain('Northstar Vehicle Service Contract')
    expect(html).toContain('Prior authorization | Section 4')
    expect(html).toContain('Northstar_Vehicle_Service_Contract.pdf')
    expect(html).toContain('contract intelligence, not legal advice')
  })

  it('does not add a cover to a standalone financial statement', () => {
    const html = render(template('cash-flow-statement', 'Cash Flow Statement', 'financial-statement'))
    expect(html).not.toContain('class="packet-cover"')
  })

  it('does not duplicate a cover supplied by an editorial packet layout', () => {
    const html = render(template('board-packet', 'Board Packet'))
    expect(html.match(/class="cover"/g)).toHaveLength(1)
    expect(html).not.toContain('class="packet-cover"')
  })

  it('adds a branded cover and client-facing issue date to a final QC closeout', () => {
    const html = buildFullHtml({
      template: template('final-qc-report', 'Final Quality Control Report'),
      brand,
      inputs: { project_name: 'Nashua Garage Loop Installation', project_period: 'May 11–13, 2026' },
      contentHtml: '<h2>Report Details</h2><table><thead><tr><th>Field</th><th>Detail</th></tr></thead><tbody><tr><td>Project</td><td>Nashua</td></tr></tbody></table>',
      documentId: 'ONS-FINALQ-2026-09-14-ABC123',
      preparedDate: '2026-09-14T19:00:07.696Z',
    })
    expect(html.match(/class="packet-cover"/g)).toHaveLength(1)
    expect(html).toContain('Prepared by On Spot Solutions')
    expect(html).toContain('Issued September 14, 2026')
    expect(html).not.toContain('2026-09-14T19:00:07.696Z')
  })
})
