import { describe, expect, it } from 'vitest'
import { buildFullHtml } from '@/lib/apollo/pdf'
import { activeSections, chooseLayoutForSlug, shouldRenderToc } from '@/lib/apollo/orchestrate'
import { getCatalog, getModule } from '@/lib/apollo/packages-loader'
import type { LoadedBrand } from '@/lib/apollo/brands'
import type { Template } from '@/lib/apollo/templates'

const clientBrand: LoadedBrand = {
  slug:'kit:pilot-client',
  label:'Northstar Fabrication',
  logo_file:null,
  logo_path:null,
  logo_bytes:null,
  logo_mime:null,
  brand_md:'# Northstar Fabrication',
}

const deliverables = getCatalog().industries
  .filter(industry => industry.status === 'active')
  .flatMap(industry => industry.deliverables)

function sectionBody(label:string) {
  return `<h2>${label}</h2><p>This section records verified pilot evidence, accountable ownership, operational status, and the next required decision.</p><table><thead><tr><th>Item</th><th>Status</th></tr></thead><tbody><tr><td>Verified evidence</td><td>VERIFIED</td></tr><tr><td>Owner review</td><td>PENDING</td></tr></tbody></table>`
}

describe('complete catalog rendering matrix', () => {
  for (const deliverable of deliverables) it(`${deliverable.slug} renders through its production layout without identity leakage`, () => {
    const module = getModule(deliverable.slug)!
    const template: Template = {
      slug:deliverable.slug,
      label:deliverable.label,
      description:deliverable.description,
      category:deliverable.industry_slug,
      supports_images:true,
      has_signature_block:['sow','proposal','contract-package','engagement-letter','nda','change-order'].includes(deliverable.slug),
      has_toc:shouldRenderToc(deliverable.slug),
      layout:chooseLayoutForSlug(deliverable.slug),
      fields:[],
      sections:module.sections.map(section => ({ id:section.key, title:section.label })),
      generation_notes:'',
    }
    const contentHtml = module.sections.map(section => sectionBody(section.label)).join('') + (deliverable.slug === 'fsr' ? '<table><tbody><tr><td>Signature: __________</td><td>Date: __________</td></tr></tbody></table>' : '')
    const html = buildFullHtml({
      template,
      brand:clientBrand,
      inputs:{ entity_name:'Northstar Fabrication', project_name:'Northstar Pilot', prepared_by:'Operations Team' },
      contentHtml,
      documentId:`NOR-${deliverable.slug.toUpperCase()}`,
      preparedDate:'September 14, 2026',
    })

    expect(html).toMatch(/^<!DOCTYPE html>/i)
    expect(html).toContain('Northstar Fabrication')
    expect(html).not.toMatch(/Generated by APOLLO|On Spot Solutions/i)
    expect(html).not.toMatch(/<script\b|<iframe\b|```|>\s*(?:undefined|null)\s*</i)
    const requiredBodySections = activeSections({ slug:deliverable.slug, deliverableLabel:deliverable.label, industryLabel:deliverable.industry_slug, module, schema:{}, style:{ id:'pilot', industry_slug:deliverable.industry_slug, label:'Pilot', description:'', content:'' }, brand:clientBrand, fields:{}, uploads:[] }).filter(section => section.required && !/^(?:cover page|title slide)$/i.test(section.label)).length
    expect((html.match(/<h2\b/gi) ?? []).length).toBeGreaterThanOrEqual(requiredBodySections)
    if (deliverable.slug === 'change-order') {
      expect(html).toContain('class="signatures-page"')
      expect(html).toContain('Northstar Fabrication')
    }
    if (['fsr','incident-report'].includes(deliverable.slug)) {
      expect(html).toContain('class="cf-masthead"')
      expect(html).toContain('class="cf-signatures"')
      expect(html).not.toContain('Signature: __________')
      expect(html).not.toContain('class="toc-page"')
      expect(html).not.toContain('class="cover"')
    }
    if (['pitch-deck','exec-presentation'].includes(deliverable.slug)) {
      expect(html).toContain('class="presentation-cover"')
      expect(html).toMatch(/class="presentation-slide\s+(?:sparse|standard|dense)"/)
      expect(html).toContain('@page { size: 13.333in 7.5in;')
      expect(html).not.toContain('class="toc-page"')
      expect(html).not.toContain('class="section-opener"')
    }
    if (/\b(?:packet|package)\b/i.test(`${deliverable.slug} ${deliverable.label}`) || deliverable.slug === 'final-qc-report') {
      expect(html.match(/class="(?:packet-)?cover"/g)).toHaveLength(1)
    }
  })
})
