'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, FileUp, Orbit, Palette, SlidersHorizontal, Users } from 'lucide-react'
import type { ConversationTurn, DeliverableSpecification, MissionTurnResult } from '@/lib/mission-control/contracts'

type Brand = { id:string; name:string; source:string; primary_color?:string|null; accent_color?:string|null }
const STORAGE_KEY='apollo:mission-control:v1'

export function MissionLaunchStudio(){
  const router=useRouter(); const [brands,setBrands]=useState<Brand[]>([]); const [working,setWorking]=useState(false); const [error,setError]=useState('')
  useEffect(()=>{fetch('/api/mission-control/brand-kits').then(r=>r.ok?r.json():{brand_kits:[]}).then(b=>setBrands(b.brand_kits??[])).catch(()=>setBrands([]))},[])
  async function launch(event:FormEvent<HTMLFormElement>){
    event.preventDefault();setWorking(true);setError('');const formElement=event.currentTarget;const form=new FormData(formElement)
    const objective=String(form.get('objective')??'').trim(); const audience=String(form.get('audience')??'').trim(); const deadline=String(form.get('deadline')??'').trim(); const format=String(form.get('format')??'PDF'); const brand=String(form.get('brand')??'apollo'); const files=form.getAll('evidence').filter((f):f is File=>f instanceof File&&f.size>0)
    const auraKeys=['authority','warmth','technicality','restraint','urgency','prestige','visual_density']; const aura=Object.fromEntries(auraKeys.map(k=>[k,Number(form.get(k))])); const auraSummary=auraKeys.map(k=>`${k.replace('_',' ')} ${aura[k]}/100`).join(', ')
    const message=[objective,audience&&`Primary audience: ${audience}.`,deadline&&`Deadline: ${deadline}.`,`Required format: ${format}.`,`Presentation calibration: ${auraSummary}.`].filter(Boolean).join(' ')
    try{
      const response=await fetch('/api/mission-control/interpret',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message,brand_profile_id:brand,aura})});const result=await response.json() as MissionTurnResult&{error?:string};if(!response.ok)throw new Error(result.error||'Mission could not be initialized')
      let specification:DeliverableSpecification=result.specification;let version=result.specification_version??1
      if(result.conversation_id){for(const file of files){const upload=new FormData();upload.set('conversation_id',result.conversation_id);upload.set('file',file);const secured=await fetch('/api/mission-control/evidence',{method:'POST',body:upload});const body=await secured.json();if(!secured.ok)throw new Error(body.error||`Could not secure ${file.name}`);specification=body.specification??specification;version=body.specification_version??version}}
      const now=new Date().toISOString();const turns:ConversationTurn[]=[{id:'opening',role:'apollo',content:'Advanced mission intake received. APOLLO has assembled the first controlled brief.',createdAt:now},{id:crypto.randomUUID(),role:'user',content:message,createdAt:now},{id:crypto.randomUUID(),role:'apollo',content:[result.acknowledgement,result.question].filter(Boolean).join('\n\n'),reason:result.question_reason,createdAt:now}]
      localStorage.setItem(STORAGE_KEY,JSON.stringify({turns,specification,readiness:result.readiness,conversationId:result.conversation_id??null,specificationVersion:version,jobId:null,jobState:null,artifactUrl:null}));router.push('/dashboard')
    }catch(cause){setError(cause instanceof Error?cause.message:'Mission launch failed');setWorking(false)}
  }
  return <div className="launch-studio"><header><div className="mc-kicker"><Orbit/> ADVANCED MISSION INTAKE <span>CONTROLLED</span></div><h1>Engineer the launch brief.</h1><p>Start with the outcome. Add precision where it helps; APOLLO will still surface assumptions and consequential gaps.</p></header><form onSubmit={launch}><section className="launch-primary"><span>01 · MISSION INTENT</span><label>What must be accomplished?<textarea required minLength={20} name="objective" placeholder="Describe the outcome, decision, or action this deliverable must produce…"/></label><div className="launch-fields"><label><Users/>Primary audience<input name="audience" placeholder="Organization, decision-maker, or reader"/></label><label>Decision deadline<input name="deadline" type="date"/></label><label>Required output<select name="format"><option>PDF</option><option>DOCX</option><option>XLSX</option></select></label></div><label className="brand-drop"><FileUp/><strong>Add available evidence</strong><span>PDF, DOCX, XLSX, CSV, text, PNG, or JPG</span><input name="evidence" multiple type="file" accept=".pdf,.docx,.xlsx,.csv,.txt,.png,.jpg,.jpeg"/></label></section><aside><section><span><Palette/>02 · BRAND SYSTEM</span><label>Mission brand<select name="brand"><option value="apollo">Apollo Master</option>{brands.map(brand=><option key={brand.id} value={`kit:${brand.id}`}>{brand.name}</option>)}</select></label><div className="launch-brand-preview">{brands.slice(0,3).map(brand=><i key={brand.id} title={brand.name} style={{background:`linear-gradient(135deg,${brand.primary_color||'#172832'},${brand.accent_color||'#5ee7ff'})`}}/>)}<small>{brands.length} custom kits in custody</small></div></section><section><span><SlidersHorizontal/>03 · AURA CALIBRATION</span>{[['authority',75],['warmth',45],['technicality',70],['restraint',68],['urgency',35],['prestige',65],['visual_density',55]].map(([key,value])=><label className="launch-slider" key={key}>{String(key).replace('_',' ')}<input name={String(key)} type="range" min="0" max="100" defaultValue={value}/></label>)}</section><button disabled={working}>{working?'Engineering mission…':<>Initialize controlled mission <ArrowRight/></>}</button>{error&&<p className="mc-error">{error}</p>}</aside></form></div>
}
