// Legacy yesterday-templates loader.
//
// Reads from templates-data.generated.ts (committed, regenerated by the
// predev / prebuild npm hooks) so the templates content is bundled into
// the JS chunk — zero runtime file dependency. Same reason as
// packages-loader.ts: outputFileTracingIncludes is unreliable with the
// --turbopack production build on Vercel, and the older flat templates
// dir was hitting the same ENOENT failure mode.
//
// Public API (listTemplates / loadTemplate / validateInputs) is unchanged.
//
// Yesterday's templates dir is preserved on disk and remains the source
// of truth — the generated file is a build artifact derived from it.

import { TEMPLATES_RAW } from './templates-data.generated'

export type FieldType = 'text' | 'textarea' | 'date' | 'number' | 'select' | 'multi_select'
export type SectionType = 'fixed' | 'prose' | 'hybrid'

export interface TemplateField {
  id: string
  label: string
  type: FieldType
  required?: boolean
  placeholder?: string
  help?: string
  default?: string | number
  options?: string[]
}

export interface TemplateSection {
  id: string
  // Older templates use `label`+`type`. Gold-standard rewrites (starting
  // with nda.json) use `title` only — section type is implied by the
  // surrounding layout. Both shapes coexist because section metadata is
  // only used by generation prompts; pdf.ts walks <h2> tags in Claude's
  // output rather than reading this array directly.
  label?: string
  title?: string
  type?: SectionType
}

export interface Template {
  slug: string
  label: string
  description: string
  category: string
  supports_images: boolean
  has_signature_block?: boolean
  // Skip the Table of Contents page. Defaults to true. Set false for
  // templates whose format doesn't warrant a TOC — letters, invoices,
  // one-pagers, single-page docs, etc.
  has_toc?: boolean
  // High-level document layout. Defaults to "contract" (cover + TOC +
  // numbered sections + signatures). Other layouts take very different
  // shapes and are handled by specialized renderers in pdf.ts.
  layout?:
    | 'contract'
    | 'letter'
    | 'invoice'
    | 'one-pager'
    | 'minutes'
    | 'financial-statement'
  fields: TemplateField[]
  sections: TemplateSection[]
  generation_notes: string
}

// Diagnostic wrapper. If a generated template entry is malformed (e.g.,
// missing required keys after a future codegen change) the consuming
// route can surface real context instead of an opaque 500.
export class TemplatesLoadError extends Error {
  constructor(
    message: string,
    public readonly cause?: unknown
  ) {
    super(message)
    this.name = 'TemplatesLoadError'
  }
}

let cache: Template[] | null = null

function shapeTemplate(slug: string, raw: unknown): Template {
  if (!raw || typeof raw !== 'object') {
    throw new TemplatesLoadError(`templates-data: entry for "${slug}" is not an object`)
  }
  const t = raw as Template
  if (typeof t.slug !== 'string' || t.slug !== slug) {
    throw new TemplatesLoadError(
      `templates-data: entry "${slug}" has slug="${t.slug}" — filename mismatch`
    )
  }
  if (typeof t.label !== 'string') {
    throw new TemplatesLoadError(`templates-data: entry "${slug}" missing label`)
  }
  return t
}

function buildCache(): Template[] {
  const list: Template[] = []
  for (const [slug, raw] of Object.entries(TEMPLATES_RAW)) {
    list.push(shapeTemplate(slug, raw))
  }
  list.sort((a, b) => a.label.localeCompare(b.label))
  return list
}

function ensureCache(): Template[] {
  if (!cache) {
    try {
      cache = buildCache()
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      throw new TemplatesLoadError(
        `Failed to build templates cache: ${message} (entries=${Object.keys(TEMPLATES_RAW).length})`,
        err
      )
    }
  }
  return cache
}

export async function listTemplates(): Promise<Template[]> {
  return ensureCache()
}

export async function loadTemplate(slug: string): Promise<Template | null> {
  const safe = slug.replace(/[^a-z0-9-]/gi, '')
  if (safe !== slug) return null
  const all = ensureCache()
  return all.find((t) => t.slug === safe) ?? null
}

export function validateInputs(
  template: Template,
  inputs: Record<string, unknown>
): { ok: true } | { ok: false; missing: string[] } {
  const missing: string[] = []
  for (const field of template.fields) {
    if (!field.required) continue
    const value = inputs[field.id]
    if (value === undefined || value === null) {
      missing.push(field.id)
      continue
    }
    if (typeof value === 'string' && value.trim() === '') {
      missing.push(field.id)
      continue
    }
  }
  return missing.length === 0 ? { ok: true } : { ok: false, missing }
}
