import Link from 'next/link'
import { Rocket } from 'lucide-react'

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-950 text-white">
      <header className="border-b border-gray-800 px-6 py-4">
        <Link href="/" className="flex items-center gap-2 w-fit">
          <Rocket className="w-6 h-6 text-red-500" />
          <span className="font-bold text-lg">Apollo MC</span>
        </Link>
      </header>
      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <p className="text-gray-400 text-sm mb-8">Last updated: March 21, 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Apollo MC (&quot;the Service&quot;), operated by On Spot Solutions LLC
              (&quot;Company,&quot; &quot;we,&quot; &quot;us&quot;), a Massachusetts limited liability company, you agree
              to be bound by these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Apollo MC is an AI-powered document generation platform. Customers select an industry,
              deliverable type, and style, provide intake information, and receive professionally
              formatted documents including but not limited to legal memoranda, business plans,
              pitch decks, compliance reports, and government proposals.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. License to Delivered Files</h2>
            <p>
              Upon successful payment, you receive a non-exclusive, non-transferable, perpetual license
              to use the delivered document for your internal business purposes. You may not:
            </p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Redistribute, resell, sublicense, or publicly share the delivered file</li>
              <li>Remove, alter, or obscure any embedded watermarks or identification markers</li>
              <li>Claim the document was created without AI assistance where disclosure is required by law</li>
              <li>Use the document as a template to offer competing document generation services</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Watermark and Enforcement</h2>
            <p>
              All delivered files contain a steganographic buyer identification watermark. This watermark
              is invisible and does not affect the appearance or usability of the document. It is used
              solely to trace unauthorized redistribution. Removal or attempted removal of the watermark
              constitutes a material breach of these Terms and may result in account termination and
              legal action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Screenshot and Reproduction Prohibition</h2>
            <p>
              You may not screenshot, photograph, or otherwise reproduce delivered documents for the
              purpose of sharing with unauthorized parties. Degraded preview versions shown during
              review are for evaluation purposes only and may not be captured or distributed.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. AI Accuracy Disclaimer</h2>
            <p>
              Documents generated by Apollo MC are produced using artificial intelligence. While we
              strive for accuracy and professionalism, AI-generated content may contain errors,
              omissions, or inaccuracies. All delivered documents should be reviewed by a qualified
              professional before use in any legal, financial, regulatory, or business context.
              On Spot Solutions LLC is not a law firm, accounting firm, or licensed professional
              services provider. The Service does not constitute legal, financial, or professional advice.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Payment Terms</h2>
            <p>
              Payment is required before delivery of the production file. Prices are displayed at the
              time of deliverable selection and confirmed in the Mission Brief before execution begins.
              All payments are processed securely through Stripe. Prices are in US Dollars.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Refund Policy</h2>
            <p>
              You may cancel a mission and receive a full refund at any time before approving the
              Mission Brief. Once the Mission Brief is approved and execution begins, no refunds
              will be issued. If the Service fails to deliver a document due to a system error,
              a full refund will be issued automatically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the security of your account credentials. You must
              not share your account or delivery links with unauthorized parties. You must provide
              accurate information during intake. Providing false or misleading information may result
              in account suspension.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Intellectual Property</h2>
            <p>
              The Apollo MC platform, brand, interface, style templates, and underlying technology
              are the intellectual property of On Spot Solutions LLC. Your license extends only to
              the specific deliverable files you have paid for.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, On Spot Solutions LLC shall not be liable for
              any indirect, incidental, special, consequential, or punitive damages arising from your
              use of the Service or delivered documents. Our total liability shall not exceed the
              amount you paid for the specific deliverable at issue.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your account at any time for violation of
              these Terms or for any reason at our sole discretion. Upon termination, your license to
              use previously delivered files survives, but your access to the platform and file
              re-download capability will be revoked.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the
              Commonwealth of Massachusetts, without regard to its conflict of law provisions. Any
              disputes arising under these Terms shall be subject to the exclusive jurisdiction of
              the state and federal courts located in Suffolk County, Massachusetts.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">14. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms at any time. Material changes will be
              communicated via email to your registered account address. Continued use of the Service
              after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">15. Contact</h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="mailto:support@apollomc.ai" className="text-red-400 hover:text-red-300">
                support@apollomc.ai
              </a>
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-800 text-center text-gray-600 text-sm">
          <p>On Spot Solutions LLC — Boston, Massachusetts</p>
          <div className="mt-2 flex items-center justify-center gap-4">
            <Link href="/privacy" className="text-gray-500 hover:text-gray-300">Privacy Policy</Link>
          </div>
        </div>
      </main>
    </div>
  )
}
